// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchEngine.Controller.DataBase;

namespace SearchEngine.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SearchEngine.Model.Entities.Document", b =>
                {
                    b.Property<string>("DocumentPath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordText")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DocumentPath");

                    b.HasIndex("WordText");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SearchEngine.Model.Entities.Word", b =>
                {
                    b.Property<string>("WordText")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WordText");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SearchEngine.Model.Entities.Document", b =>
                {
                    b.HasOne("SearchEngine.Model.Entities.Word", null)
                        .WithMany("OccurredDocuments")
                        .HasForeignKey("WordText");
                });

            modelBuilder.Entity("SearchEngine.Model.Entities.Word", b =>
                {
                    b.Navigation("OccurredDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
