name: build

on:
  push:
    branches:
    - main
    - Phase6
    
  pull_request:
    branches:
    - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
     
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Phase05/SearchEngine
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Phase05/SearchEngine
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Phase05/SearchEngine







